# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d72581156e09fd81b4ec53aa2f748eca240b76fda80850eca5eb5e84f74c71a383ceea6a636ae44f3da7d504d4238211352eb78ad84d90b8a58483196ce244fc

test:
  secret_key_base: ebc0bf3e7cb40a4f526ea52099b947603224ded6236510573138798f0170e5b017803920a3e0473b84e886963ec692aaa781c2b558ee20053648cd927ed8afed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
